// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/moq77111113/chmoly-santas/ent/exclusion"
	"github.com/moq77111113/chmoly-santas/ent/group"
	"github.com/moq77111113/chmoly-santas/ent/member"
	"github.com/moq77111113/chmoly-santas/ent/predicate"
)

// ExclusionQuery is the builder for querying Exclusion entities.
type ExclusionQuery struct {
	config
	ctx         *QueryContext
	order       []exclusion.OrderOption
	inters      []Interceptor
	predicates  []predicate.Exclusion
	withGroup   *GroupQuery
	withMember  *MemberQuery
	withExclude *MemberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExclusionQuery builder.
func (eq *ExclusionQuery) Where(ps ...predicate.Exclusion) *ExclusionQuery {
	eq.predicates = append(eq.predicates, ps...)
	return eq
}

// Limit the number of records to be returned by this query.
func (eq *ExclusionQuery) Limit(limit int) *ExclusionQuery {
	eq.ctx.Limit = &limit
	return eq
}

// Offset to start from.
func (eq *ExclusionQuery) Offset(offset int) *ExclusionQuery {
	eq.ctx.Offset = &offset
	return eq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eq *ExclusionQuery) Unique(unique bool) *ExclusionQuery {
	eq.ctx.Unique = &unique
	return eq
}

// Order specifies how the records should be ordered.
func (eq *ExclusionQuery) Order(o ...exclusion.OrderOption) *ExclusionQuery {
	eq.order = append(eq.order, o...)
	return eq
}

// QueryGroup chains the current query on the "group" edge.
func (eq *ExclusionQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exclusion.Table, exclusion.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, exclusion.GroupTable, exclusion.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMember chains the current query on the "member" edge.
func (eq *ExclusionQuery) QueryMember() *MemberQuery {
	query := (&MemberClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exclusion.Table, exclusion.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, exclusion.MemberTable, exclusion.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExclude chains the current query on the "exclude" edge.
func (eq *ExclusionQuery) QueryExclude() *MemberQuery {
	query := (&MemberClient{config: eq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exclusion.Table, exclusion.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, exclusion.ExcludeTable, exclusion.ExcludeColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Exclusion entity from the query.
// Returns a *NotFoundError when no Exclusion was found.
func (eq *ExclusionQuery) First(ctx context.Context) (*Exclusion, error) {
	nodes, err := eq.Limit(1).All(setContextOp(ctx, eq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{exclusion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eq *ExclusionQuery) FirstX(ctx context.Context) *Exclusion {
	node, err := eq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Exclusion ID from the query.
// Returns a *NotFoundError when no Exclusion ID was found.
func (eq *ExclusionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eq.Limit(1).IDs(setContextOp(ctx, eq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{exclusion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eq *ExclusionQuery) FirstIDX(ctx context.Context) int {
	id, err := eq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Exclusion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Exclusion entity is found.
// Returns a *NotFoundError when no Exclusion entities are found.
func (eq *ExclusionQuery) Only(ctx context.Context) (*Exclusion, error) {
	nodes, err := eq.Limit(2).All(setContextOp(ctx, eq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{exclusion.Label}
	default:
		return nil, &NotSingularError{exclusion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eq *ExclusionQuery) OnlyX(ctx context.Context) *Exclusion {
	node, err := eq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Exclusion ID in the query.
// Returns a *NotSingularError when more than one Exclusion ID is found.
// Returns a *NotFoundError when no entities are found.
func (eq *ExclusionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eq.Limit(2).IDs(setContextOp(ctx, eq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{exclusion.Label}
	default:
		err = &NotSingularError{exclusion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eq *ExclusionQuery) OnlyIDX(ctx context.Context) int {
	id, err := eq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Exclusions.
func (eq *ExclusionQuery) All(ctx context.Context) ([]*Exclusion, error) {
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryAll)
	if err := eq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Exclusion, *ExclusionQuery]()
	return withInterceptors[[]*Exclusion](ctx, eq, qr, eq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eq *ExclusionQuery) AllX(ctx context.Context) []*Exclusion {
	nodes, err := eq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Exclusion IDs.
func (eq *ExclusionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if eq.ctx.Unique == nil && eq.path != nil {
		eq.Unique(true)
	}
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryIDs)
	if err = eq.Select(exclusion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eq *ExclusionQuery) IDsX(ctx context.Context) []int {
	ids, err := eq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eq *ExclusionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryCount)
	if err := eq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eq, querierCount[*ExclusionQuery](), eq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eq *ExclusionQuery) CountX(ctx context.Context) int {
	count, err := eq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eq *ExclusionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eq.ctx, ent.OpQueryExist)
	switch _, err := eq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eq *ExclusionQuery) ExistX(ctx context.Context) bool {
	exist, err := eq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExclusionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eq *ExclusionQuery) Clone() *ExclusionQuery {
	if eq == nil {
		return nil
	}
	return &ExclusionQuery{
		config:      eq.config,
		ctx:         eq.ctx.Clone(),
		order:       append([]exclusion.OrderOption{}, eq.order...),
		inters:      append([]Interceptor{}, eq.inters...),
		predicates:  append([]predicate.Exclusion{}, eq.predicates...),
		withGroup:   eq.withGroup.Clone(),
		withMember:  eq.withMember.Clone(),
		withExclude: eq.withExclude.Clone(),
		// clone intermediate query.
		sql:  eq.sql.Clone(),
		path: eq.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ExclusionQuery) WithGroup(opts ...func(*GroupQuery)) *ExclusionQuery {
	query := (&GroupClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withGroup = query
	return eq
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ExclusionQuery) WithMember(opts ...func(*MemberQuery)) *ExclusionQuery {
	query := (&MemberClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withMember = query
	return eq
}

// WithExclude tells the query-builder to eager-load the nodes that are connected to
// the "exclude" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *ExclusionQuery) WithExclude(opts ...func(*MemberQuery)) *ExclusionQuery {
	query := (&MemberClient{config: eq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eq.withExclude = query
	return eq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GroupID int `json:"group_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Exclusion.Query().
//		GroupBy(exclusion.FieldGroupID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eq *ExclusionQuery) GroupBy(field string, fields ...string) *ExclusionGroupBy {
	eq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExclusionGroupBy{build: eq}
	grbuild.flds = &eq.ctx.Fields
	grbuild.label = exclusion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GroupID int `json:"group_id,omitempty"`
//	}
//
//	client.Exclusion.Query().
//		Select(exclusion.FieldGroupID).
//		Scan(ctx, &v)
func (eq *ExclusionQuery) Select(fields ...string) *ExclusionSelect {
	eq.ctx.Fields = append(eq.ctx.Fields, fields...)
	sbuild := &ExclusionSelect{ExclusionQuery: eq}
	sbuild.label = exclusion.Label
	sbuild.flds, sbuild.scan = &eq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExclusionSelect configured with the given aggregations.
func (eq *ExclusionQuery) Aggregate(fns ...AggregateFunc) *ExclusionSelect {
	return eq.Select().Aggregate(fns...)
}

func (eq *ExclusionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eq); err != nil {
				return err
			}
		}
	}
	for _, f := range eq.ctx.Fields {
		if !exclusion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eq.path != nil {
		prev, err := eq.path(ctx)
		if err != nil {
			return err
		}
		eq.sql = prev
	}
	return nil
}

func (eq *ExclusionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Exclusion, error) {
	var (
		nodes       = []*Exclusion{}
		_spec       = eq.querySpec()
		loadedTypes = [3]bool{
			eq.withGroup != nil,
			eq.withMember != nil,
			eq.withExclude != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Exclusion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Exclusion{config: eq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eq.withGroup; query != nil {
		if err := eq.loadGroup(ctx, query, nodes, nil,
			func(n *Exclusion, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := eq.withMember; query != nil {
		if err := eq.loadMember(ctx, query, nodes, nil,
			func(n *Exclusion, e *Member) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	if query := eq.withExclude; query != nil {
		if err := eq.loadExclude(ctx, query, nodes, nil,
			func(n *Exclusion, e *Member) { n.Edges.Exclude = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eq *ExclusionQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*Exclusion, init func(*Exclusion), assign func(*Exclusion, *Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Exclusion)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (eq *ExclusionQuery) loadMember(ctx context.Context, query *MemberQuery, nodes []*Exclusion, init func(*Exclusion), assign func(*Exclusion, *Member)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Exclusion)
	for i := range nodes {
		fk := nodes[i].MemberID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (eq *ExclusionQuery) loadExclude(ctx context.Context, query *MemberQuery, nodes []*Exclusion, init func(*Exclusion), assign func(*Exclusion, *Member)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Exclusion)
	for i := range nodes {
		fk := nodes[i].ExcludeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "exclude_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (eq *ExclusionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eq.querySpec()
	_spec.Node.Columns = eq.ctx.Fields
	if len(eq.ctx.Fields) > 0 {
		_spec.Unique = eq.ctx.Unique != nil && *eq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eq.driver, _spec)
}

func (eq *ExclusionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(exclusion.Table, exclusion.Columns, sqlgraph.NewFieldSpec(exclusion.FieldID, field.TypeInt))
	_spec.From = eq.sql
	if unique := eq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eq.path != nil {
		_spec.Unique = true
	}
	if fields := eq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exclusion.FieldID)
		for i := range fields {
			if fields[i] != exclusion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if eq.withGroup != nil {
			_spec.Node.AddColumnOnce(exclusion.FieldGroupID)
		}
		if eq.withMember != nil {
			_spec.Node.AddColumnOnce(exclusion.FieldMemberID)
		}
		if eq.withExclude != nil {
			_spec.Node.AddColumnOnce(exclusion.FieldExcludeID)
		}
	}
	if ps := eq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eq *ExclusionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eq.driver.Dialect())
	t1 := builder.Table(exclusion.Table)
	columns := eq.ctx.Fields
	if len(columns) == 0 {
		columns = exclusion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eq.sql != nil {
		selector = eq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eq.ctx.Unique != nil && *eq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eq.predicates {
		p(selector)
	}
	for _, p := range eq.order {
		p(selector)
	}
	if offset := eq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExclusionGroupBy is the group-by builder for Exclusion entities.
type ExclusionGroupBy struct {
	selector
	build *ExclusionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (egb *ExclusionGroupBy) Aggregate(fns ...AggregateFunc) *ExclusionGroupBy {
	egb.fns = append(egb.fns, fns...)
	return egb
}

// Scan applies the selector query and scans the result into the given value.
func (egb *ExclusionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, egb.build.ctx, ent.OpQueryGroupBy)
	if err := egb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExclusionQuery, *ExclusionGroupBy](ctx, egb.build, egb, egb.build.inters, v)
}

func (egb *ExclusionGroupBy) sqlScan(ctx context.Context, root *ExclusionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(egb.fns))
	for _, fn := range egb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*egb.flds)+len(egb.fns))
		for _, f := range *egb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*egb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := egb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExclusionSelect is the builder for selecting fields of Exclusion entities.
type ExclusionSelect struct {
	*ExclusionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (es *ExclusionSelect) Aggregate(fns ...AggregateFunc) *ExclusionSelect {
	es.fns = append(es.fns, fns...)
	return es
}

// Scan applies the selector query and scans the result into the given value.
func (es *ExclusionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, es.ctx, ent.OpQuerySelect)
	if err := es.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExclusionQuery, *ExclusionSelect](ctx, es.ExclusionQuery, es, es.inters, v)
}

func (es *ExclusionSelect) sqlScan(ctx context.Context, root *ExclusionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(es.fns))
	for _, fn := range es.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*es.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := es.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
